apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-local-repo
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
