apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: helm-chart-oci-publish
  namespace: ${ENVIRONMENT}
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: helm-chart-oci-publish
      bindings:
        - ref: helm-chart-oci-publish
      template:
        ref: helm-chart-oci-publish
