apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: helm-chart-oci-publish
  namespace: infra
spec:
  params:
    - name: namespace
    - name: repository
    - name: helm-charts-dir
      default: charts
    - name: helm-registry
      default: oci://artifactory-jcr.infra.svc.cluster.local:8082/docker-local
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: helm-chart-oci-publish-run-
        namespace: infra
      spec:
        pipelineRef:
          name: helm-chart-oci-publish
        podTemplate:
          securityContext:
            fsGroup: 65532
        serviceAccountName: tekton-pipeline
        workspaces:
          - name: helm-source
            volumeClaimTemplate:
              metadata:
                labels:
                  tekton.dev/pvc-protection-finalizer: remove
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          - name: manifest-dir
            volumeClaimTemplate:
              metadata:
                labels:
                  tekton.dev/pvc-protection-finalizer: remove
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Mi
          - name: docker-config
            secret:
              secretName: docker-config
          - name: ssh-directory
            secret:
              secretName: ssh-credentials
        params:
          - name: namespace
            value: $(tt.params.namespace)
          - name: repository
            value: $(tt.params.repository)
          - name: helm-charts-dir
            value: $(tt.params.helm-charts-dir)
          - name: helm-registry
            value: $(tt.params.helm-registry)
