apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: helm-chart-oci-publish
  namespace: ${ENVIRONMENT}
spec:
  params:
    - name: namespace
      value: $(body.involvedObject.namespace)
    - name: repository
      value: $(body.involvedObject.name)
    - name: charts-dir
      value: $(body.metadata.chartsDir)
    - name: excluded-charts
      value: $(body.metadata.excludedCharts)
    - name: registry
      value: $(body.metadata.registry)
