apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: node-helm
  namespace: ${ENVIRONMENT}
spec: 
  params:
  - name: namespace
    value: $(body.involvedObject.namespace)
  - name: repository
    value: $(body.involvedObject.name)
  - name: node-context-dir
    value: $(body.metadata.nodeContextDir)
  - name: node-build-output-dir
    value: $(body.metadata.nodeBuildOutputDir)
  - name: helm-chart-repo-url
    value: $(body.metadata.helmChartRepoUrl)
  - name: helm-chart-repo-revision
    value: $(body.metadata.helmChartRepoRevision)
  - name: helm-chart-release-namespace
    value: $(body.metadata.helmChartReleaseNamespace)
  - name: charts-dir
    value: $(body.metadata.chartsDir)
